Change to accept regex without /
byjg/php-swagger-test pull request #71
Opened 2021-10-04 07:44 UTC by vitormattos

The parser of https://stoplight.io/ don't accept / on regex pattern.

To accept pattern with and without / I created a method to prepare the pattern before use.

2021-10-04 08:19 UTC, froschdesign commented
> The parser of https://stoplight.io/ don't accept / on regex pattern.

It is irrelevant who accepts something or not. Only the specification is important: https://swagger.io/docs/specification/data-models/data-types/#pattern 😃

2021-10-04 16:58 UTC, byjg commented
You're right. The OpenAPI specification is the only one we should base on. 

Double-checking the link you sent with the specification makes sense for this PR since the initial and final `/` are not required for the RegEx ECMA 262 but just for the PHP `preg_match`.

2021-10-04 16:59 UTC, byjg requested changes

2021-10-04 16:59 UTC, byjg commented on src/Base/Body.php
> +        $pattern = $this->preparePattern($pattern);
You can just do:

```
$pattern = "/" . rtrim(ltrim($pattern, "/"), "/") . "/"
```

2021-10-05 14:08 UTC, byjg approved these changes

2021-10-05 14:09 UTC, merged

2021-10-05 14:11 UTC, byjg commented
Thanks. Version 3.1.4 published.